### ISSUE TITLE
詳解遮擋住題目

### ISSUE THREAD

**Issue by jackychiu0207** [SiongSng/cap-countdown#1]
在手機上使用chrome瀏覽網頁版
答錯題目後點擊詳解
會遮擋住題目
![Screenshot_20230313-232629_Chrome.jpg](https://user-images.githubusercontent.com/66721680/224749294-69e11d17-a044-4773-9d61-d67a03247679.jpg)

**Comment by SiongSng** [comment]
感謝您的回報 我會想想看詳解更適合放置在何處
另外若您有建議放置的位置歡迎提供！

**Comment by jackychiu0207** [comment]
> 感謝您的回報 我會想想看詳解更適合放置在何處 另外若您有建議放置的位置歡迎提供！

我會覺得可以放在題目的下方
上下滑動就可以對照題目、選項和詳解

**Comment by SiongSng** [comment]
https://github.com/SiongSng/cap-countdown/pull/5
