### ISSUE TITLE
會考成績查詢連結連結建議

### ISSUE THREAD

**Issue by MinecraftPEayer** [SiongSng/cap-countdown#59]
![Screenshot_20230615-181309005_1](https://github.com/SiongSng/cap-countdown/assets/87757022/dc912224-9575-4d5e-a401-ca5221ac3460)
這個按鈕應該可以導向<https://score.rcpet.edu.tw/>
而不是<https://cap.rcpet.edu.tw/>

**Comment by SiongSng** [comment]
非常感謝您的建議，這部分當初我不清楚具體是什麼連結，所以先暫放官網，後來公布成績後我的想法跟你一樣，改成這個連結。

預計於下個版本發佈，感謝建議。

**Comment by MinecraftPEayer** [comment]
剛開始查詢的確是<https://cap.rcpet.edu.tw/>
但過不久就會變回去

**Comment by SiongSng** [comment]
https://github.com/SiongSng/cap-countdown/commit/45564067c1bfcad8b6a1cd91f91e311356acd177
